### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by antgr** [sebastianruder/sluice-networks#5]
After solving the TypeError: parameter() got an unexpected keyword argument 'update' 
with the following modification:
\-        penalty = dynet.parameter(self.subspace_penalty, update=False)
\+        print ("self.subspace_penalty", self.subspace_penalty)
I have yet another error:
Training epoch 1/30...task_name pos
output_expected_at_layer 2
self.subspace_penalty <_dynet.Parameters object at 0x7fbaf3d664c8>
len(lstm_parameters) 3
W_shape (400, 100)
W_shape (400,)
Traceback (most recent call last):
  File "run_sluice_net.py", line 231, in <module>
    main(args)
  File "run_sluice_net.py", line 119, in main
    train_dir=args.train_dir, dev_dir=args.dev_dir)
  File "/home/ant/multitask/sluice-networks/sluice_net.py", line 319, in fit
    output, penalty = self.predict(features, task, train=True)
  File "/home/ant/multitask/sluice-networks/sluice_net.py", line 446, in predict
    self.num_subspaces), W_shape[1]))
IndexError: tuple index out of range

**Comment by antgr** [comment]
The error is in this code:

                    print ("len(lstm_parameters)", len(lstm_parameters)) <--- 0,1,2
                    for param_idx in range(len(lstm_parameters)):
                        print ("param_idx", param_idx)
                        print ("self.constrain_matrices", self.constrain_matrices)
                        **W = lstm_parameters[param_idx]**
                        print ("lstm_parameters[param_idx]", W.value())
                        **if param_idx in self.constrain_matrices:**
                            W = lstm_parameters[param_idx]
                            #print ("lstm_parameters[param_idx]", W.value())
                            **W_shape = np.array(W.value()).shape**
                            print ("W_shape",W_shape)
                            # split matrix into its two subspaces
                            W_subspaces = dynet.reshape(W, (
                                self.num_subspaces, W_shape[0] / float(
                                    self.num_subspaces), **W_shape[1]**))
                            subspace_1, subspace_2 = W_subspaces[0], W_subspaces[1]

I can inspect that:
self.constrain_matrices [1, 2]
lstm_parameters[0] : (**W_shape (400, 264)**)
[[-0.06852068 -0.05971083 -0.09073808 ... -0.00424316  0.01182706
  -0.03177004]
 [-0.07256807  0.0169341  -0.07710622 ... -0.03384282  0.01911698
   0.08084721]
 [ 0.0382052  -0.00263168  0.07310223 ... -0.06098209  0.0193444
  -0.01597825]
 ...
 [-0.00942036  0.03853537  0.04613553 ...  0.06374234 -0.02973958
  -0.00685045]
 [ 0.07659535 -0.01242224 -0.04037898 ...  0.00118123 -0.02281301
   0.00879992]
 [ 0.08706602 -0.00343869  0.03164638 ... -0.05354206  0.09320351
   0.01756171]]


lstm_parameters[1] :  (**W_shape (400, 100)**)
 [[ 0.07192101  0.03745154 -0.04265522 ...  0.02616856 -0.03004232
   0.06226604]
 [-0.07246315 -0.10788991 -0.10169568 ...  0.0594859   0.02911491
  -0.03852709]
 [ 0.08393983 -0.06241827  0.05435176 ...  0.02497289 -0.10620279
   0.0674325 ]
 ...
 [ 0.05095783 -0.02378532  0.08029653 ...  0.06019973  0.0428394
   0.07717284]
 [ 0.07006429 -0.00781979 -0.07818662 ...  0.03552618  0.06189073
   0.0852089 ]
 [ 0.03464752  0.02230508 -0.00671343 ... -0.07282209  0.07760502
   0.07110591]]

lstm_parameters[2]   (**W_shape (400,)**)
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

**Comment by antgr** [comment]
**Task chunk. Labels: []**  (\*)
That means that the issue, **lstm_parameters[2] (W_shape (400,))** has to do with this(*).
We have to follow the step regarding chunks:
**python PTB2chunks.py --original-folder  conll-formatted-ontonotes-5.0/data/train/data/english/ --conll-folder ontonotes-5.0/train/data/english/**
output:
['conll-formatted-ontonotes-5.0/train/data/english/annotations', 'conll-formatted-ontonotes-5.0/test/data/english/annotations', 'conll-formatted-ontonotes-5.0/development/data/english/annotations', 'conll-formatted-ontonotes-5.0/conll-2012-test/data/english/annotations'] original-ontonotes-5.0/annotations
Traceback (most recent call last):
  File "PTB2chunks.py", line 169, in <module>
    conll_folder='conll-formatted-ontonotes-5.0')
  File "PTB2chunks.py", line 35, in convertOntonotesChunks
    for fold in conll_folders_data + original_folder_data:
TypeError: can only concatenate list (not "str") to list

Seems that all the issues have to do with the dataset and missing steps on the dataset formatting.
I will come back if i solve all the issues.

**Comment by antgr** [comment]
@sebastianruder sebastianruder

**Comment by sebastianruder** [comment]
Sorry, I unfortunately don't have time to actively maintain this project any longer.

**Comment by antgr** [comment]
@sebastianruder  OK! Thanks for the code! And for the response! 
But just to be consistent with myself, the phrase 'any longer' sounds odd, as there are no other responses. Thanks anyway.

**Comment by antgr** [comment]
No problem. Thanks for all the maintenance you provided until today.
